name: flutter_modney
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  animated_theme_switcher: ^2.0.8
  carousel_slider: ^4.2.1
  dart_code_metrics: ^5.7.6
  dio: ^5.3.3
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_facebook_auth: ^5.0.11
  flutter_local_notifications: ^15.1.1
  flutter_naver_login: ^1.8.0
  flutter_signin_button: ^2.0.0
  flutter_svg: ^2.0.7
  footer: ^0.0.4
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  go_router: ^11.0.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.5
  hexcolor: ^3.0.1
  http: ^0.13.6
  image_editor: ^1.3.0
  image_picker: ^1.0.4
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  kakao_flutter_sdk: ^1.6.0
  mockito: ^5.4.2
  numberpicker: ^2.1.2
  page_transition: ^2.1.0
  photo_view: ^0.14.0
  provider: ^6.0.5
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

   
flutter:
  uses-material-design: true
  assets:
      - assets/
      - assets/icon/
      - assets/image/
      - assets/svg/
      - assets/lottie/